### ISSUE TITLE
Error PrintEventsForDatapoint.py

### ISSUE THREAD

**Issue by tocks53** [sarnau/InsideViessmannVitosoft#3]
Hello,
I have an error with the PrintEventsForDatapoint.py, when i change :
 parse_Textresource('fr') # load english localization, 'de' is German
        parse_ecnEventTypes()
        parse_DPDefinitions('CU401B_S')

 python PrintEventsForDatapoint.py
VT200 WO1C
==========
Traceback (most recent call last):
  File "PrintEventsForDatapoint.py", line 478, in <module>
    parse_DPDefinitions('CU401B_S')
  File "PrintEventsForDatapoint.py", line 324, in parse_DPDefinitions
    eventValueType['Stepping'] = int(eventValueType['Stepping'])
ValueError: invalid literal for int() with base 10: '0.5'

Can you confirm is ok on your system ?

Thanks

**Comment by sarnau** [comment]
It seems 0.5 is a possible stepping value. Try changing int(…) to float(…)

**Comment by tocks53** [comment]
Hi @sarnau , thanks for your reply.

Now i have an another error

`python PrintEventsForDatapoint.py
VT200 WO1C
==========
()
# Vue d'ensemble (19728)
- Installation (19693)
    - Température extérieure (7692) [WPR3_Aussentemperatur~0x01C1 (SInt)] HIDDEN:("Température extérieure"="Sonde  indisponible")
    - Temp. de départ installation (7710) [WPR3_Anlagenvorlauf~0x01CA (SInt)] HIDDEN:("Départ installation"="Sonde  indisponible")
    - Etat de fonctionnement installation (8525) [WPR3_Betriebsstatus_Anlage~0x1188 (Byte)]
    - Saison de chauffe CC1 (8045) [WPR3_Geraetestatus_Heizperiode_HK1~0x1410 (Byte)] HIDDEN:("CC1 existant"="Non")
    - Saison de chauffe CC2 (8046) [WPR3_Geraetestatus_Heizperiode_HK2~0x1410 (Byte)] HIDDEN:("CC2 existant"="Non")
    - Saison de chauffe CC3 (8047) [WPR3_Geraetestatus_Heizperiode_HK3~0x1410 (Byte)] HIDDEN:("CC3 existant"="Non")
    - Saison de rafraîch. CC1 (8048) [WPR3_Geraetestatus_Kuehlperiode_HK1~0x1410 (Byte)] HIDDEN:("CC1 existant"="Non" OR "Circuit de chauffage 1 fonction de rafraîchissement existant"="Non")
    - Saison de rafraîch. CC2 (8049) [WPR3_Geraetestatus_Kuehlperiode_HK2~0x1410 (Byte)] HIDDEN:("CC2 existant"="Non" OR "Circuit de chauffage 2 fonction de rafraîchissement existant"="Non")
    - Saison de rafraîch. CC3 (8050) [WPR3_Geraetestatus_Kuehlperiode_HK3~0x1410 (Byte)] HIDDEN:("CC3 existant"="Non" OR "Circuit de chauffage 3 fonction de rafraîchissement existant"="Non")
    - Température du réservoir tampon (7712) [WPR3_Pufferspeichertemperatur_1~0x01CB (SInt)] HIDDEN:("Température du réservoir tampon"="Sonde  indisponible")
    - Mode de fonct. réserv. tampon (7323) [WPR_WO1H_GueltBetriebsmodus_Pufferspeicher~0x1184 (Int)]
    - Etat relais M2 vanne mél. FER (6691) [WPR_RelaisStatus_M2_MischerZU~0x04B3 (Byte)]
    - Tempér. fluide du GC externe (7722) [WPR3_Externer_WE~0x01CC (SInt)] HIDDEN:("Tempér. fluide du GC externe"="Sonde  indisponible")
    - Commande générateur chaleur ext. (6656) [WPR_RelaisStatus_Ansteuerung_ExtWaermeerzeuger~0x048B (Byte)]
    - Commande générateur chaleur ext. (6596) [WPR_RelaisLaufzeiten_Ansteuerung_ExtWaermeerzeuger~0x058B (Int4)] HIDDEN:("Génér. chaleur ext. existant"="Non existant")
    - Alarme centralisée (8528) [WPR3_Sammelstoerung~0x0491 (Byte)]
    - Mode de fonct. piscine (7330) [WPR_WO1H_GueltBetriebsmodus_Schwimmbad~0x1186 (Int)] HIDDEN:("Piscine existante"="Non existant""Piscine existante"="Non")
    - Etat relais piscine vanne (6703) [WPR_RelaisStatus_Schwimmbad_Ventil~0x0497 (Byte)] HIDDEN:("Piscine existante"="Non")
Traceback (most recent call last):
  File "PrintEventsForDatapoint.py", line 478, in <module>
    parse_DPDefinitions('CU401B_S')
  File "PrintEventsForDatapoint.py", line 464, in parse_DPDefinitions
    print('    - ' + eventTypeStr(eventType))
  File "PrintEventsForDatapoint.py", line 462, in eventTypeStr
    result += condStr
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)
`
