### ISSUE TITLE
Error PrintEventsForDatapoint.py

### ISSUE THREAD

**Issue by uelpenich** [sarnau/InsideViessmannVitosoft#8]
I try to run the InsideViessmannVitosoft Python scripts on a Windows11 system. 
I use the Python 3.10 (64) Interpreter and PyCharm Community Edition 2022.1.4

The scripts **PrintDatapoints.py** and **PrintEventTypes.py** work fine and deliver the expected results. 

The script **PrintEventsForDatapoint.py** exits with code 1:

> C:\Users\Werner\AppData\Local\Programs\Python\Python310\python.exe C:/Users/Werner/Documents/InsideViessmannVitosoft-main/PrintEventsForDatapoint.py
> Traceback (most recent call last):
>   File "C:\Users\Werner\Documents\InsideViessmannVitosoft-main\PrintEventsForDatapoint.py", line 505, in <module>
>     parse_DPDefinitions('VScotHO1_70')
>   File "C:\Users\Werner\Documents\InsideViessmannVitosoft-main\PrintEventsForDatapoint.py", line 160, in parse_DPDefinitions
>     root = etree.fromstring(re.sub(' xmlns="[^"]+"', '', open(DATAPATH + "DPDefinitions.xml", 'r').read()))
>   File "C:\Users\Werner\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1344, in XML
>     parser.feed(text)
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
> 
> Process finished with exit code 1

Vitosoft 300 Software has run successfully and delivered all information about my heater unit. 

Any idea what is wrong? Thanks.

**Comment by LFrank2021** [comment]
@sarnau 
I am facing the same problem.
Is there another solution for this than to use another Python interpreter?

**Comment by sarnau** [comment]
I do not use Windows, so I don't know this issue. Could be a text encoding issue on Windows?!?

**Comment by philippoo66** [comment]
First of all thank you VERYYYY much for your great work @sarnau Michael!!!

And yes, I experienced the same issue and I found the solution. There are three bytes right at the beginning of the xml which does not work (with windows?). simply removing them solved the issue.

{#}   root = etree.fromstring(re.sub(' xmlns="[^"]+"', '', open(DATAPATH + "DPDefinitions.xml",'r').read()))
    mystr = open(DATAPATH + "DPDefinitions.xml",'r').read()
    mystr = re.sub(' xmlns="[^"]+"', '', mystr)
    mystr = mystr[3:]       <----  this solves the problem
    root = etree.fromstring(mystr)

With certain devices ('datapoints') there will raise some issues that Int data can't get parsed to Int (section 'Stepping') and some like that but in most cases the script runs fine. 

For everybody who doesn't like so install the Vitosoft monster and and deal with sh.. I put up the DP Lists [here](https://github.com/philippoo66/ViessData21) (DP_Listen_2.zip). You find some csv files in there - this is where the script fails and I took at least the addresses etc from the SQL database. Does not look that fine as Michael's output but contains the important info. 

greetings!
Phil

**Comment by sarnau** [comment]
These 3 bytes might be the UTF-8 marker. Please check the exact values, are they EF BB BF? See [https://en.wikipedia.org/wiki/Byte_order_mark](https://en.wikipedia.org/wiki/Byte_order_mark)

**Comment by philippoo66** [comment]
bingo!
